### ISSUE TITLE
Fatal error: Call to undefined function wp_is_mobile()

### ISSUE THREAD

**Issue by joegasper** [ProjectNami/projectnami-blob-cache#12]
Full error received (only text displayed on page after steps below):

Fatal error: Call to undefined function wp_is_mobile() in D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\project-nami-blob-cache.php on line 209

Line 209 area:

209: if ( wp_is_mobile() ) {
210: $url = $url . "|mobile";
211: }

I'm running in Azure, automated install via the Install to Azure button.
Running latest WP 4.5.1 (deployment sync)
Project Nami Blob Cache version 3.0

Changes since install:
Moved to a multi-site setup using sub-folders.
Standard wp-config.php change for multisite. Added WP provided URL rewrite rules.
Used this technique to not have to strip my site (not prod) to enable sub-folder config:
http://www.wpoptimus.com/334/solution-old-wordpress-installation-sub-directory-network/

To reproduce the error above.
At the Network level for plugins, perform a Network Activation for the PN Blob Cache.

To recover from the error, comment out line 209-211 in the specified PHP file, and Network Deactivate the PN Blob Cache.

The PN Blob Cache activates fine in sites.

PN Full Text Search does active at the Network level.

Cheers,
Joe

**Comment by Vidocq24601** [comment]
I can confirm that this is still an issue. 

On a PN multisite installation using subdomains: Network Activating the PN Blob Cache plugin results in the same fatal error as outlined by Joe in May 2016.

**Comment by AnikShen** [comment]
Dear support, 

my customer reported the same issue when run it on azure web app, can you help check if blob cache plugin is supported in  Azure web app. anyone got chance to make it work on Azure web app?

does it hit any azure web app sandbox limit?
https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

Thanks,

**Comment by patrickebates** [comment]
We're looking again at the Network Activation issue.

Regarding the sandbox limit, yes it is possible to hit those limits at Free and Shared with Blob Cache if your site is receiving that much traffic.  But then you would have reached those limits even earlier without Blob Cache (specifically CPU).

**Comment by Vidocq24601** [comment]
Patrick,

Were there any updates regarding the Network Activation issue?

Thanks,

**Comment by patrickebates** [comment]
We're looking at releasing a new version soon with a couple of minor updates, one of which may be to simply drop the "mobile theme" support which requires the use of wp_is_mobile.  It's not an issue with responsive themes.  By removing the check, the Network Activation should take care of itself.

**Comment by Vidocq24601** [comment]
Hi Patrick,

Do you have an update or timeline with regards to an update that will address the network activation issue?

Thanks,

**Comment by Vidocq24601** [comment]
Patrick,

Do you have any additional developments or information pertaining to the fatal error when network activating the project nami blob cache plugin on a multisite installation?

Is there a workaround other than activating on a per site basis? The concern with activating per site is that if inadvertently network activated, the plugin would bring down the entire network. The team is aware of the issue, however in this scenario, all it would take is a single 'oops click' and then fatal errors across the multisite. 

Thanks,

**Comment by patrickebates** [comment]
Sorry, thought I had replied to this.  I haven't put together a ZIP package yet, but you should find that the code change has been committed to both of the repositories.  This one, and the DLL.

https://github.com/ProjectNami/projectnami-blob-cache/commit/c807063cb4efd6b971f7bb73764c9103ee5104bb

https://github.com/ProjectNami/ProjectNamiBlobCache/commit/164c341817b4814e14fcda39f6e9548cfc0051e1

**Comment by joegasper** [comment]
Patrick, do you have a zip (compiled) available please? Thanks.

**Comment by patrickebates** [comment]
Here's the updated DLL alone.
https://projectnami.blob.core.windows.net/cache/ProjectNamiBlobCache.dll

**Comment by joegasper** [comment]
Thank you. Network activated with no issues.
