### ISSUE TITLE
WooCommerce: Excluding pages from the cache

### ISSUE THREAD

**Issue by erikest** [ProjectNami/projectnami-blob-cache#13]
Hey guys,

Been using your blob cache plugin, which works great, except... :)

We're using WooCommerce and visitors noticed that they can add items to their cart, but they can't see them.  This looks like it is caused by the cache serving up a cached empty cart page.  I disabled the blob cache plugin and voila, carts show up as expected.

Is there a way to exclude certain pages from the cache?

Here's a woocommerce support page describing what to do with other cache plugins:
https://docs.woothemes.com/document/configuring-caching-plugins/

**Comment by patrickebates** [comment]
Settings -> PN Blob Cache

Simply add the full URL of each page as a comma separated list in the Exclusions box.

**Comment by erikest** [comment]
Of Course!  So many plugins and they all put there stuff in different
places...  Clearly, I'm a wp newb :)

On Thu, Jun 9, 2016 at 12:23 PM, Patrick Bates <notifications@github.com>
wrote:

> Settings -> PN Blob Cache
>
> Simply add the full URL of each page as a comma separated list in the
> Exclusions box.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ProjectNami/projectnami-blob-cache/issues/13#issuecomment-224999533>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS3kQRivFXeBkzD-oXC0jWb3ovgr4d4Dks5qKGglgaJpZM4IySml>
> .
>



-- 
-Erik
