### ISSUE TITLE
Enabling projectnami-blob-cache prevents media upload

### ISSUE THREAD

**Issue by charlesroddie** [ProjectNami/projectnami-blob-cache#16]
Enabling this plugin (projectnami-blob-cache v 3.0) prevents upload of files to the media library on my Wordpress site. Uploaded files are not written. There are no useful error messages that I can see.

I'm not sure if this is related to https://github.com/ProjectNami/projectnami-blob-cache/issues/14

The Project Nami site was set up 5 months ago using "deploy to Azure". 

I think these files reside on an Azure storage account with "Performance: Standard", "SKU Standard_RAGRS".

Grateful for any info on how to get this working or what other caching is compatible with Project Nami. Thanks.

**Comment by patrickebates** [comment]
Haven't seen anything like this before.  Are you using the media library locally, or are you using a plugin to redirect the media library to an Azure Blob Storage account?

**Comment by charlesroddie** [comment]
We made some trivial changes and reactivated the plugin and media upload problems have gone away.

The caching still isn't working.

We had Azure Blob storage as part of the original Nami setup.

We followed the instructions, with minor things not working out:
9) Enter the values for your Blob Account and set the Time To Live for cached pages
**blob account not asked for in settings, only expiry time and exceptions
10) Build this project, then create a Bin folder at the root of your site and upload the two DLL files produced by the build into the Bin folder.
**there were three DLLs, Microsoft.WindowsAzure.Storage, Newtonsoft.Json, and ProjectNamiBlobCache, so we put these all in
11) Copy the provided web.config file into the root of your site, or if you already have a web.config file instead merge the contents into your existing file.
**There was no provided file but we found to put the following from http://projectnami.org/project-nami-blob-cache-build-2-now-available
<modules>
    <add name="ProjectNamiBlobCache" type="ProjectNamiBlobCache.CacheFrontEnd" />
</modules>

We don't get any caching and we don't get either of the expected comments when viewing the site:



Thanks very much for any help!

**Comment by patrickebates** [comment]
Do you have both of the required components installed?  In addition to the plugin, you need the IIS module installed as well.  Please see the following complete package.
https://projectnami.blob.core.windows.net/cache/project-nami-blob-cache-3.0.1.zip

Also, caching only takes place for public users (those not logged into WordPress).

**Comment by charlesroddie** [comment]
Thanks a lot for your help!
Could be a login issue but I made the update anyway.
I am getting "". Does that indicate projectnami-blob-cache is active?

**Comment by patrickebates** [comment]
Yes, that is reporting the milliseconds required for the IIS module to evaluate the request and retrieve the page from cache.  I was thinking we had changed the output from what you listed above.

The only concern I have is that 367 ms is a relatively long time.  What size Web App are you running, and is the Storage account in the same Azure data center?  The last time I recall seeing values that high was on a Shared or Free site.

https://easyhealthoptions.com is a great production example of Blob Cache, and it routinely reports 15 ms to 50 ms.

**Comment by charlesroddie** [comment]
Great, glad we have got this working. Thanks again.

And you're right, we need to move one of our Azure regions!
