### ISSUE TITLE
PHP Error Log

### ISSUE THREAD

**Issue by Vidocq24601** [ProjectNami/projectnami-blob-cache#17]
**Reviewing php_errors.log, there are a series of repeating errors displayed below:**

`PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable in D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\project-nami-blob-cache.php on line 418`

**Between lines 417 and 433 of project-nami-blob-cache.php:**

	public function handle_output_buffer( $output_buffer ) {

		// Bail if the output buffer is empty
		if( sizeof( $output_buffer ) < 1 )
			return $output_buffer;

		//$elements = array( '<html', '<head', '<body', '</html', '</head', '</body', '<rss', '</rss' );

		//foreach( $elements as $element ) {
		//	if( substr_count( $output_buffer, $element ) < 1 )
		//		return $output_buffer;
		//}
			
		$this->cache_page_content( $output_buffer );
		
		$duration = round( microtime( true ) - $this->initial_timestamp, 3 );
        	
		return str_replace( '</head>', "\n</head>", $output_buffer );
	}

**From code above and the description below:**

_If you'd like to see how long it's taking to generate your pages, you can view the page source. Just before the closing head tag ( </head> ), you'll find the following:_

When the page is not served from the cache:

`<!-- Page generated without caching in *your generation time* seconds. -->`

When the page is served from the cache:

`<!-- Served by Project Nami Blob Cache in *time with caching* seconds. -->`

**However when viewing page source**

Neither string is displayed (before </head> or elsewhere). As an additional verification, validated this was also true here: view-source:https://easyhealthoptions.com/.

Can you provide guidance as to whether these two issues are related or unrelated? In either case, next steps to identify a solution to one or both issues would be greatly appreciated. 

Thanks as always Patrick.

**Comment by patrickebates** [comment]
So the issue with sizeof was corrected by Spencer with commit https://github.com/ProjectNami/projectnami-blob-cache/commit/af266a2c35cf6f2a3ec4b48ce24b7fd94177bd7d but it seems we didn't prepare an updated release.  You can download the files from this repo to get the update.

Regarding the viewing of the page cache to see the data in the HEAD, to do so you must not be logged into WordPress in the browser instance (logged in users always bypass the cache).  I suggest trying again using private/incognito mode.

**Comment by patrickebates** [comment]
Oh, you also need an App Setting of ProjectNamiBlobCache.Debug equal to 1 for that data to be generated too.  The plugin only writes to the cache, and the IIS module only reads from the cache.  Both will check for that same setting to generate output.

**Comment by Vidocq24601** [comment]
Ah thank you. Just wasn't obvious to me output would only be generated if debug setting had been enabled from the readme, my mistake. Makes sense and appreciate your help. Working as expected.
