### ISSUE TITLE
Feature Request: Add functionality to exclude pages from cache

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami-blob-cache#4]
We should have a UI where URLs could be added to a list of "don't cache" pages.

**Comment by craigomatic** [comment]
+1

**Comment by CalamitousPanda** [comment]
Fixed by this merge: https://github.com/ProjectNami/projectnami-blob-cache/pull/5
:)

**Comment by pippercameron** [comment]
Thanks, @CalamitousPanda! Closing this out.
